
project_id = "nrrtzvmvgtbjomdxlufl"

# Define edge function settings
[functions.generate-image]
verify_jwt = false # Allow the function to be called without authentication

[functions.makeReal]
verify_jwt = false # Allow the function to be called without authentication
