
project_id = "nrrtzvmvgtbjomdxlufl"

# Define edge function settings
[functions.generate-image]
verify_jwt = false # Allow the function to be called without authentication

[functions.makeReal]
verify_jwt = false # Allow the function to be called without authentication

# Storage configuration
[storage]
file_size_limit = "5MB"

# Storage bucket specific configurations
[[storage.buckets]]
name = "generated-images"
public = true
file_size_limit = "5MB"
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg"]
