// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrrtzvmvgtbjomdxlufl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ycnR6dm12Z3Riam9tZHhsdWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDg1MjEsImV4cCI6MjA2MjQ4NDUyMX0.ERVHpyX6KMuZy85BhIjskXaD3o5FwbpVMS9JUeZhcvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);